/*
SafePay API

API for SafePay services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSettingsResponseStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSettingsResponseStatus{}

// ApiSettingsResponseStatus struct for ApiSettingsResponseStatus
type ApiSettingsResponseStatus struct {
	Errors []string `json:"errors,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewApiSettingsResponseStatus instantiates a new ApiSettingsResponseStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSettingsResponseStatus() *ApiSettingsResponseStatus {
	this := ApiSettingsResponseStatus{}
	return &this
}

// NewApiSettingsResponseStatusWithDefaults instantiates a new ApiSettingsResponseStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSettingsResponseStatusWithDefaults() *ApiSettingsResponseStatus {
	this := ApiSettingsResponseStatus{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ApiSettingsResponseStatus) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsResponseStatus) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApiSettingsResponseStatus) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ApiSettingsResponseStatus) SetErrors(v []string) {
	o.Errors = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiSettingsResponseStatus) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsResponseStatus) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiSettingsResponseStatus) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiSettingsResponseStatus) SetMessage(v string) {
	o.Message = &v
}

func (o ApiSettingsResponseStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSettingsResponseStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableApiSettingsResponseStatus struct {
	value *ApiSettingsResponseStatus
	isSet bool
}

func (v NullableApiSettingsResponseStatus) Get() *ApiSettingsResponseStatus {
	return v.value
}

func (v *NullableApiSettingsResponseStatus) Set(val *ApiSettingsResponseStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSettingsResponseStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSettingsResponseStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSettingsResponseStatus(val *ApiSettingsResponseStatus) *NullableApiSettingsResponseStatus {
	return &NullableApiSettingsResponseStatus{value: val, isSet: true}
}

func (v NullableApiSettingsResponseStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSettingsResponseStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


