/*
SafePay API

API for SafePay services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GuestResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuestResponseData{}

// GuestResponseData struct for GuestResponseData
type GuestResponseData struct {
	Session *string `json:"session,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewGuestResponseData instantiates a new GuestResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuestResponseData() *GuestResponseData {
	this := GuestResponseData{}
	return &this
}

// NewGuestResponseDataWithDefaults instantiates a new GuestResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuestResponseDataWithDefaults() *GuestResponseData {
	this := GuestResponseData{}
	return &this
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *GuestResponseData) GetSession() string {
	if o == nil || IsNil(o.Session) {
		var ret string
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestResponseData) GetSessionOk() (*string, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *GuestResponseData) HasSession() bool {
	if o != nil && !IsNil(o.Session) {
		return true
	}

	return false
}

// SetSession gets a reference to the given string and assigns it to the Session field.
func (o *GuestResponseData) SetSession(v string) {
	o.Session = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *GuestResponseData) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuestResponseData) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *GuestResponseData) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *GuestResponseData) SetToken(v string) {
	o.Token = &v
}

func (o GuestResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuestResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Session) {
		toSerialize["session"] = o.Session
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableGuestResponseData struct {
	value *GuestResponseData
	isSet bool
}

func (v NullableGuestResponseData) Get() *GuestResponseData {
	return v.value
}

func (v *NullableGuestResponseData) Set(val *GuestResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGuestResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGuestResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuestResponseData(val *GuestResponseData) *NullableGuestResponseData {
	return &NullableGuestResponseData{value: val, isSet: true}
}

func (v NullableGuestResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuestResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


