/*
SafePay API

API for SafePay services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuthResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthResponseData{}

// AuthResponseData struct for AuthResponseData
type AuthResponseData struct {
	Session *string `json:"session,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewAuthResponseData instantiates a new AuthResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthResponseData() *AuthResponseData {
	this := AuthResponseData{}
	return &this
}

// NewAuthResponseDataWithDefaults instantiates a new AuthResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthResponseDataWithDefaults() *AuthResponseData {
	this := AuthResponseData{}
	return &this
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *AuthResponseData) GetSession() string {
	if o == nil || IsNil(o.Session) {
		var ret string
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResponseData) GetSessionOk() (*string, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *AuthResponseData) HasSession() bool {
	if o != nil && !IsNil(o.Session) {
		return true
	}

	return false
}

// SetSession gets a reference to the given string and assigns it to the Session field.
func (o *AuthResponseData) SetSession(v string) {
	o.Session = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AuthResponseData) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResponseData) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AuthResponseData) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AuthResponseData) SetToken(v string) {
	o.Token = &v
}

func (o AuthResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Session) {
		toSerialize["session"] = o.Session
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableAuthResponseData struct {
	value *AuthResponseData
	isSet bool
}

func (v NullableAuthResponseData) Get() *AuthResponseData {
	return v.value
}

func (v *NullableAuthResponseData) Set(val *AuthResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthResponseData(val *AuthResponseData) *NullableAuthResponseData {
	return &NullableAuthResponseData{value: val, isSet: true}
}

func (v NullableAuthResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


